Implementa cache de escritura, mejora a cache de lectura y cambios varios
jokoframework/wilson pull request #4
Opened 2019-10-03 17:13 UTC by gabrielci

- Endpoint Maestro de Wilson para requests POST que intenta primeramente hacer pasar el request al Backend y si se falla por problemas de conexión
    aplica el cache de escritura si este se activo para el recurso
    
- Endpoints de Operaciones de Escritura para poder insertar y obtener las operaciones que se habilitaron para el Cache de escritura
    
- Servicios de Cache de Escritura para poder guardar y actualizar requests de escritura en cache y servicios del Worker para ejecutar un cache de escritura
    
- Esqueleto de WriteOperation y Write Cache implementados (Controller con Endpoints con Seguridad, Service, ServiceImpl, Repository)
    
- Worker de escritura que trata de ejecutar las operaciones en cache con un estado en particular y maneja los estados de cada entrada
    
- Se introdujo una clase de Response y de Request propia debido a problemas con Spring Data, ReadCache paso a ser ResponseCache y
    se creo la clase RequestCache
    
- Arreglos del Sonar, incluyendo algunos TODOS que quedaron de la funcionalidad de Lectura
    
- Una pasada final a todo el proyecto para tratar de dejar todo comentado y agregar TODOS que faltaban

2019-10-03 19:00 UTC, alefq requested changes

2019-10-03 19:00 UTC, alefq commented on RUN.md
> +* Base de datos MongoDB
Colocar versiones exactas de las bases de datos con las que se recomienda ejecutar.

2019-10-03 19:00 UTC, alefq commented on src/main/java/io/github/jokoframework/wilson/cache/repositories/WriteOperationRepository.java
> +}
Es una recomendación dejar siempre una línea en blanco al final de los archivos de tipo texto.

2019-10-03 19:00 UTC, alefq commented on src/main/java/io/github/jokoframework/wilson/cache/enums/ReadHttpVerbEnum.java
> +    GET
¿Cuál es la justificación para tener los verbs http separados? 
¿por qué no un sólo enum para todos los verbs?

2019-10-03 19:00 UTC, alefq commented on src/main/java/io/github/jokoframework/wilson/scheduler/ScheduledTasks.java
> +        ScheduledTasks.accessToken = accessToken;
Se creó el WIL-17 para mejorar este manejo de `static`.

2019-10-04 17:10 UTC, gabrielci commented on src/main/java/io/github/jokoframework/wilson/cache/enums/ReadHttpVerbEnum.java
> +    GET
Esos Enums guardan los valores validos para el campo "Request Type" en las tablas de Escritura y Lectura respectivamente, si se juntara todo en uno podria darle el valor GET al "Request Type" de una operación de escritura y seria un registro muerto dentro de la tabla.

2019-10-08 19:10 UTC, gabrielci commented on RUN.md
> +* Base de datos MongoDB
Ademas de lo pedido se agrego la versión de Maven

2019-10-08 19:16 UTC, gabrielci commented on src/main/java/io/github/jokoframework/wilson/cache/repositories/WriteOperationRepository.java
> +}
Se recorrieron todos los archivos de Wilson que se agregaron hasta el momento al proyecto base y se aplico esta recomendación donde faltaba

2019-10-11 13:39 UTC, alefq approved these changes

2019-10-11 13:39 UTC, merged